name: Deploy to [Platform/Service]

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to [Platform/Service]
        uses: [Platform/Service]-login-action@v1
        with:
          username: ${{ secrets.[PLATFORM/SERVICE_USERNAME] }}
          password: ${{ secrets.[PLATFORM/SERVICE_PASSWORD] }}
      - name: Deploy to [Platform/Service]
        run: [Platform/Service] deploy --config [config file]
